//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cdk")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Text", unique)]
    pub cdk: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub uuid: Option<String>,
    pub plan: i32,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub used_time: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub used_by: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
