//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::cdk::Entity as Cdk;
pub use super::cdk::ActiveModel as CdkModel;
pub use super::order::Entity as Order;
pub use super::order::ActiveModel as OrderModel;
